name: Deploy code-path to Nexus and Server

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Nexus Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker.code-path.tech
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker.code-path.tech/code-path:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 49172
          script: |
            cd /containers/infra-code-path/landing-page-code-path
            echo "${{ secrets.NEXUS_PASSWORD }}" | docker login docker.code-path.tech -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin
            docker-compose pull
            docker-compose up -d --remove-orphans